### ISSUE TITLE
Installation über Contao Manager

### ISSUE THREAD

**Issue by 9teufel** [marcosimbuerger/contao-isotope-print-multiple-documents#2]
Danke für die Erweiterung! 

Würde sie gerne testen, jedoch finde ich sie nicht über den Contao Manager.

**Comment by marcosimbuerger** [comment]
Hi @mecintosch 

Das Modul ist eigentlich nicht gedacht, um es im Manager/Packagist zu veröffentlichen. Das kann ich aber noch machen.
Wenn Du es schon mal testen willst, kannst Du das Repo einfach in Deiner `composer.json` angeben. Danach kannst Du es installieren mit `composer require marcosimbuerger/contao-isotope-print-multiple-documents
`
```
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/marcosimbuerger/contao-isotope-print-multiple-documents.git"
    }
],
```

**Comment by 9teufel** [comment]
Hab das Paket als zip über den Contao Manager hochgeladen. Funktioniert einwandfrei - danke!

**Comment by marcosimbuerger** [comment]
Das Modul ist jetzt bei packagist vorhanden und kann normal via composer installiert werden: https://packagist.org/packages/marcosimbuerger/contao-isotope-print-multiple-documents
