### ISSUE TITLE
Verschiedensprachige Dokumente => Übersetzung Land

### ISSUE THREAD

**Issue by 9teufel** [marcosimbuerger/contao-isotope-print-multiple-documents#3]
Sobald verschiedensprachige Dokumente gemeinsam generiert werden, ist die Übersetzung von $arrBillingAddress->country und $arrShippingAddress->country nicht mehr in der richtigen Sprache.

Es steht dann in einem DE Dokument Germany oder Allemagne statt Deutschland.

Die Dokumente erstelle ich mithilfe [katgirl / isotope_documents](https://github.com/katgirl/isotope_documents), das Template sieht so aus:

```
<?php

  use Isotope\Isotope;

  $this->loadLanguageFile('countries');
  $this->loadLanguageFile('tl_iso_config');
  include(TL_ROOT . '/system/config/countries.php');
  $arrBillingAddress = $this->collection->getBillingAddress();
  $arrShippingAddress = $this->collection->getShippingAddress();
  $objConfig = Isotope::getConfig();
?>

<?php echo $GLOBALS['TL_LANG']['CNT'][$arrBillingAddress->country]; ?>
```

Wenn die Dokumente einzeln erstellt werden, so stimmt die Übersetzung natürlich immer.

Vielen Dank für die Hilfe!

**Comment by marcosimbuerger** [comment]
Hi @mecintosch

Mein Modul verwendet für die Generierung der Dokumente die gleiche Funktion, wie Isotope selbst. Es wird auch die Methode `loadOrderEnvironment() `aufgerufen, welche dann die Sprache setzt (https://github.com/isotope/core/blob/master/system/modules/isotope/library/Isotope/Frontend.php#L585). Zudem ist die Sprache auch auf der Order selbst hinterlegt.

Ich kenne das katgirl-isotope_documents Modul nicht. Kannst Du mal prüfen, was Du für Sprach-Infos in den Dokumenten hast. `$GLOBALS['TL_LANGUAGE']` und `$this->collection->language`.

**Comment by 9teufel** [comment]
Hallo,

danke für deine Antwort. 

Sowohl `$GLOBALS['TL_LANGUAGE']` als auch `$this->collection->language` geben die korrekte Sprache in Form von "de, it, fr,…" aus. Auch `echo $arrShippingAddress->country` passt, aber leider nur die Kurzform.

Im iso_documents Template ist  `include(TL_ROOT . '/system/config/countries.php');` gar nicht notwendig. Geändert hat sich aber auch nichts.

**Comment by marcosimbuerger** [comment]
Ich schliesse dieses Ticket, da der Fehler nicht auf dieses Modul zurückzuführen ist.
