### ISSUE TITLE
Funny story

### ISSUE THREAD

**Issue by bright-cloud-studio** [marcosimbuerger/contao-isotope-print-multiple-documents#5]
Hello there!

I wanted to tell you this funny little story about my last two days of work here. I work pretty much exclusively with Contao these days, specifically I am contracted out to make a lot of custom packages for people. My current task is a custom order exporter for Isotope. Specifically, they wanted me to set up a custom option in the "Select multiple" mode so you would get sent to a different screen after selecting your orders where you could tick of what you want exported into a CSV file.

Well, I have been using this package as reference, as in English there isn't much online for Contao documentation. I found your package by searching '$GLOBALS['TL_DCA']['tl_iso_product_collection']['select']['buttons_callback'][]' as I knew that is where things were leading. It only turned up your package, like I said there isn't many examples out there trying to do this sort of thing. Anyway, I followed along and thing went great until I tried changing the act from 'select' to my own version. When I tried that every time it would crash saying that doesn't exist inside DC_Table.

Well, I fought that for a few hours before rereading your whole package and discovering that you obviously had this same issue! Your solution was your other package that lets you declare inline functions inside DC_Table. Can't believe how frustrated I was and how much time I put into this before I realized that.

All in all, it was decided I would just have it dump everything and down the road if they want to customize what can be exported, we will try to go back down that route, in which case I'll be grateful for your other repo here as it seems to be the solution to my problem.

Thanks for working on both of these, I wouldn't have gotten this far without them!

**Comment by marcosimbuerger** [comment]
Hi @bright-cloud-studio,

Thank you for sharing your story!

Correct, I had exactly the same problem and the solution was my [DC extension module](https://github.com/marcosimbuerger/contao-data-container-extension).

I am glad to hear that both modules have helped you. Another nice example of the advantages of open-source! 😃 

I wish you lots of success with your Contao projects!
